"""paper capital pools and live allocated capital

Revision ID: 0569b14a23fd
Revises: 6c4fbc962253
Create Date: 2026-09-01 15:13:38.134432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0569b14a23fd'
down_revision: Union[str, None] = '6c4fbc962253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_deployments', sa.Column('allocated_capital', sa.Float(), nullable=True))
    op.add_column('live_deployments', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('paper_portfolios', sa.Column('name', sa.String(length=150), nullable=False, server_default='Default'))
    op.add_column('paper_portfolios', sa.Column('currency', sa.String(length=3), nullable=False, server_default='INR'))
    op.alter_column('paper_portfolios', 'name', server_default=None)
    op.alter_column('paper_portfolios', 'currency', server_default=None)
    op.drop_constraint(op.f('paper_portfolios_user_id_key'), 'paper_portfolios', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('paper_portfolios_user_id_key'), 'paper_portfolios', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('paper_portfolios', 'currency')
    op.drop_column('paper_portfolios', 'name')
    op.drop_column('live_deployments', 'currency')
    op.drop_column('live_deployments', 'allocated_capital')
    # ### end Alembic commands ###
