"""add backtest date range and position sizing override

Revision ID: 6c4fbc962253
Revises: 9ac334c975f6
Create Date: 2026-08-30 20:37:35.991045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c4fbc962253'
down_revision: Union[str, None] = '9ac334c975f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_jobs', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('backtest_jobs', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('backtest_jobs', sa.Column('position_sizing_type', sa.String(length=20), nullable=True))
    op.add_column('backtest_jobs', sa.Column('position_sizing_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_jobs', 'position_sizing_value')
    op.drop_column('backtest_jobs', 'position_sizing_type')
    op.drop_column('backtest_jobs', 'end_date')
    op.drop_column('backtest_jobs', 'start_date')
    # ### end Alembic commands ###
