"""add bf_symbols.last_synced_at

Revision ID: 9ac334c975f6
Revises: ae97fda264f6
Create Date: 2026-08-30 19:51:23.473609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ac334c975f6'
down_revision: Union[str, None] = 'ae97fda264f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bf_symbols', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bf_symbols', 'last_synced_at')
    # ### end Alembic commands ###
