"""phase 7: live trading

Revision ID: ec153092f13c
Revises: 2ecf76c1b6a9
Create Date: 2026-08-28 19:54:05.979917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec153092f13c'
down_revision: Union[str, None] = '2ecf76c1b6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_switch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('activated_by', sa.Uuid(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('broker_account_id', sa.Uuid(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['live_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_table('live_positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['live_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_positions')
    op.drop_table('live_orders')
    op.drop_table('live_deployments')
    op.drop_table('kill_switch')
    # ### end Alembic commands ###
